# -*- coding: utf-8 -*-
"""Untitled69.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iX6nVlDP8YBlj5ScgfbbC8JoT33J0nrl
"""

import streamlit as st
from langchain.llms import HuggingFaceEndpoint

def load_answer(question):
    llm = HuggingFaceEndpoint(repo_id="mistralai/Mistral-7B-Instruct-v0.2")
    answer = llm.invoke(question)
    return answer

# App UI starts here
st.set_page_config(page_title="Question-Answering", page_icon=":robot:")
st.header("Question-Answering")

# Gets the user input
def get_text():
    input_text = st.text_input("You: ", key="input")
    return input_text

user_input = get_text()

# If generate button is clicked and user_input is not empty
if st.button('Generate') and user_input.strip():
    response = load_answer(user_input)
    st.subheader("Answer:")
    st.write(response)
else:
    if not user_input.strip():
        st.warning("Please enter a question before generating an answer.")